AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: >
  Simple Todo List API

Globals:
  Function:
    Timeout: 3

Resources:
  TodoGet:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: todo.api.get.handler
      Runtime: python3.12
      CodeUri: .
      Description: Get ToDo items
      Policies:
        - DynamoDBCrudPolicy:
            TableName: TodoList
      Environment:
        Variables:
          TODO_TABLE: TodoList
      Events:
        ApiTodoListAPI:
          Type: Api
          Properties:
            Path: /todo
            Method: GET

  TodoCreate:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: todo.api.create.handler
      Runtime: python3.12
      CodeUri: .
      Description: Create new ToDo item
      Policies:
        - DynamoDBCrudPolicy:
            TableName: TodoList
      Environment:
        Variables:
          TODO_TABLE: TodoList
      Events:
        ApiTodoListAPI:
          Type: Api
          Properties:
            Path: /todo
            Method: POST

  TodoUpdate:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: todo.api.update.handler
      Runtime: python3.12
      CodeUri: .
      Description: Update ToDo item
      Policies:
        - DynamoDBCrudPolicy:
            TableName: TodoList
      Environment:
        Variables:
          TODO_TABLE: TodoList
      Events:
        ApiTodoListAPI:
          Type: Api
          Properties:
            Path: /todo
            Method: PUT

  TodoDelete:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: todo.api.delete.handler
      Runtime: python3.12
      CodeUri: .
      Description: Delete ToDo item
      Policies:
        - DynamoDBCrudPolicy:
            TableName: TodoList
      Environment:
        Variables:
          TODO_TABLE: TodoList
      Events:
        ApiTodoListAPI:
          Type: Api
          Properties:
            Path: /todo
            Method: DELETE
